package com.my.common.dao;

import com.my.common.model.RoleInfo;
import com.my.common.model.RoleInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Jan 13 17:30:45 CST 2015
     */
    int countByExample(RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Jan 13 17:30:45 CST 2015
     */
    int deleteByExample(RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Jan 13 17:30:45 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Jan 13 17:30:45 CST 2015
     */
    int insert(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Jan 13 17:30:45 CST 2015
     */
    int insertSelective(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Jan 13 17:30:45 CST 2015
     */
    List<RoleInfo> selectByExample(RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Jan 13 17:30:45 CST 2015
     */
    RoleInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Jan 13 17:30:45 CST 2015
     */
    int updateByExampleSelective(@Param("record") RoleInfo record, @Param("example") RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Jan 13 17:30:45 CST 2015
     */
    int updateByExample(@Param("record") RoleInfo record, @Param("example") RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Jan 13 17:30:45 CST 2015
     */
    int updateByPrimaryKeySelective(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Jan 13 17:30:45 CST 2015
     */
    int updateByPrimaryKey(RoleInfo record);
}