package com.my.common.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ID
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.LOGIN_NAME
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.PASSWORD
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.NAME
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.EMAIL
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.PHONE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ADDRESS
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.POST_CODE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.JOB_TITLE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private String jobTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.GENDERID
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private Integer genderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.CREATE_DATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.UPDATE_DATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.LOGIN_DATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private Date loginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.LAST_LOGIN_DATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private Date lastLoginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.DESCRIPTION
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.STATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.IS_LOGIN
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private Integer isLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ORGANIZATION_ID
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private Long organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.TEL
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.MSN
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private String msn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.QQ
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    private String qq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ID
     *
     * @return the value of user_info.ID
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ID
     *
     * @param id the value for user_info.ID
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.LOGIN_NAME
     *
     * @return the value of user_info.LOGIN_NAME
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.LOGIN_NAME
     *
     * @param loginName the value for user_info.LOGIN_NAME
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.PASSWORD
     *
     * @return the value of user_info.PASSWORD
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.PASSWORD
     *
     * @param password the value for user_info.PASSWORD
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.NAME
     *
     * @return the value of user_info.NAME
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.NAME
     *
     * @param name the value for user_info.NAME
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.EMAIL
     *
     * @return the value of user_info.EMAIL
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.EMAIL
     *
     * @param email the value for user_info.EMAIL
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.PHONE
     *
     * @return the value of user_info.PHONE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.PHONE
     *
     * @param phone the value for user_info.PHONE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ADDRESS
     *
     * @return the value of user_info.ADDRESS
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ADDRESS
     *
     * @param address the value for user_info.ADDRESS
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.POST_CODE
     *
     * @return the value of user_info.POST_CODE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.POST_CODE
     *
     * @param postCode the value for user_info.POST_CODE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.JOB_TITLE
     *
     * @return the value of user_info.JOB_TITLE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.JOB_TITLE
     *
     * @param jobTitle the value for user_info.JOB_TITLE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle == null ? null : jobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.GENDERID
     *
     * @return the value of user_info.GENDERID
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public Integer getGenderid() {
        return genderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.GENDERID
     *
     * @param genderid the value for user_info.GENDERID
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setGenderid(Integer genderid) {
        this.genderid = genderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.CREATE_DATE
     *
     * @return the value of user_info.CREATE_DATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.CREATE_DATE
     *
     * @param createDate the value for user_info.CREATE_DATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.UPDATE_DATE
     *
     * @return the value of user_info.UPDATE_DATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.UPDATE_DATE
     *
     * @param updateDate the value for user_info.UPDATE_DATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.LOGIN_DATE
     *
     * @return the value of user_info.LOGIN_DATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public Date getLoginDate() {
        return loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.LOGIN_DATE
     *
     * @param loginDate the value for user_info.LOGIN_DATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.LAST_LOGIN_DATE
     *
     * @return the value of user_info.LAST_LOGIN_DATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.LAST_LOGIN_DATE
     *
     * @param lastLoginDate the value for user_info.LAST_LOGIN_DATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.DESCRIPTION
     *
     * @return the value of user_info.DESCRIPTION
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.DESCRIPTION
     *
     * @param description the value for user_info.DESCRIPTION
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.STATE
     *
     * @return the value of user_info.STATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.STATE
     *
     * @param state the value for user_info.STATE
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.IS_LOGIN
     *
     * @return the value of user_info.IS_LOGIN
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public Integer getIsLogin() {
        return isLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.IS_LOGIN
     *
     * @param isLogin the value for user_info.IS_LOGIN
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setIsLogin(Integer isLogin) {
        this.isLogin = isLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ORGANIZATION_ID
     *
     * @return the value of user_info.ORGANIZATION_ID
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public Long getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ORGANIZATION_ID
     *
     * @param organizationId the value for user_info.ORGANIZATION_ID
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.TEL
     *
     * @return the value of user_info.TEL
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.TEL
     *
     * @param tel the value for user_info.TEL
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.MSN
     *
     * @return the value of user_info.MSN
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public String getMsn() {
        return msn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.MSN
     *
     * @param msn the value for user_info.MSN
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setMsn(String msn) {
        this.msn = msn == null ? null : msn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.QQ
     *
     * @return the value of user_info.QQ
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.QQ
     *
     * @param qq the value for user_info.QQ
     *
     * @mbggenerated Tue Jan 13 17:30:57 CST 2015
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }
}